### ISSUE TITLE
 完成度无法达到100%

### ISSUE THREAD

**Issue by tianshaokai** [renjianan/GifView#1]
1. 小米4
2. Android 6.0.1
3. MUI8.5稳定版

**Comment by ren93** [comment]
这个是图片绘制帧率慢导致的，计算gif的播放进度的时间是毫秒级的，但是每次调用onDraw()方法间隔远达不到1毫秒（大概在17毫秒左右），所以基本上不会正好在最后那个时间点上，而是前面几毫秒，而且这个数值也可能是不同的。简单说来说：1000毫秒的gif，3毫秒绘制一次，那第999毫秒绘制后，就直接跳过从头开始绘制第2毫秒时间点的图片了。

**Comment by renjianan** [comment]
如果想解决就四舍五入吧

**Comment by ren93** [comment]
目前解决方法就是把结果四舍五入了

**Comment by tianshaokai** [comment]
厉害

**Comment by Kenmmm** [comment]
在6.0的部分机器，gif 速度好慢！
